#!/bin/bash
#send_file_lb <datafile> <ip> <port>
set -x

bn=$(basename $1)
dn=$(dirname $1)
wd=$PWD
tag=$(echo $RANDOM | md5sum | head -c 10)
cd /tmp
if [ "$1" == "-" ] || [ "$1" == "/dev/stdin" ]; then
	split -b1024 $1 $tag
else
	split -b1024 $wd/$bn $tag
fi
S=1
for f in $tag*
do
       	wc -c $f
       	cat $f | $wd/lb_send -s $S | nc -p 7654 -U -4 -u $2 $3
       	S=$(echo $S \+ 1 | bc) 
done
rm -f $tag* 
cd $wd
