#!/bin/bash
#set -x
evnt_num=$1
evnt_sz=$2 
t=$(mktemp) 
../emulation/tst_lb_rcv1 $evnt_num > $t
t1=$(mktemp) 
for i in $(seq 17750 17765) 
    do 
        grep $i $t|grep  Event_size: >> $t1
    done
echo ' '
echo -n "Port count deficient of events: "
for i in $(seq 17750 17765) 
    do 
        grep $i $t1|wc -l
    done|grep -v $evnt_num|wc -l
echo ' '
echo -n "Port count for incorrect event size: " 
for i in $(seq 17750 17765) 
    do 
        grep $i $t1|grep "Event_size: $evnt_sz "|wc -l 
    done|grep -v $evnt_num|wc -l
echo ' '
echo -n "Number of missing/incorrect did stream sizes: "
ndss=$(for i in $(seq 17750 17765)
    do 
        grep $i $t1|grep "Event_size: $evnt_sz "
    done|grep $evnt_sz|wc -l)
echo $((16*$evnt_num - $ndss))
echo ' '
echo $t $t1
echo "reported perrors:"
grep perror $t|sort|uniq
echo ' '
echo -n "Num ports with incorrect iteration counts: "
for i in $(seq 17750 17765) 
    do 
        echo -n "Num events for $i :"
        grep $i $t1|wc -l
    done|grep -v $evnt_num|wc -l
echo ' '
echo -n "Num events with incorrect event sizes: "
for i in $(seq 17750 17765) 
    do 
        echo -n  "Num event sizes for $i :"
        grep $i $t1
    done|grep -v $evnt_sz|wc -l
echo ' '
echo -n "Num disc dids with incorrect size counts: "
ls -lt  /tmp/rs*|grep -v log|cut -f5 -d ' '|grep -v  $(($evnt_sz*$evnt_num))|wc -l
echo -n "Number of unique disc did checksums: "
for f in /tmp/rs_?????
    do sum $f
    done|sort -n|uniq|wc -l
