#!/bin/bash
#set -x
t0=$(mktemp); t0x=$(mktemp); taskset -c 0 ./bin/lb_rcv -i 129.57.109.231 -p 17750  -n $1 > $t0 2> $t0x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t1=$(mktemp); t1x=$(mktemp); taskset -c 1 ./bin/lb_rcv -i 129.57.109.231 -p 17751  -n $1 > $t1 2> $t1x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t2=$(mktemp); t2x=$(mktemp); taskset -c 2 ./bin/lb_rcv -i 129.57.109.231 -p 17752  -n $1 > $t2 2> $t2x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t3=$(mktemp); t3x=$(mktemp); taskset -c 3 ./bin/lb_rcv -i 129.57.109.231 -p 17753  -n $1 > $t3 2> $t3x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t4=$(mktemp); t4x=$(mktemp); taskset -c 4 ./bin/lb_rcv -i 129.57.109.231 -p 17754  -n $1 > $t4 2> $t4x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t5=$(mktemp); t5x=$(mktemp); taskset -c 5 ./bin/lb_rcv -i 129.57.109.231 -p 17755  -n $1 > $t5 2> $t5x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t6=$(mktemp); t6x=$(mktemp); taskset -c 6 ./bin/lb_rcv -i 129.57.109.231 -p 17756  -n $1 > $t6 2> $t6x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t7=$(mktemp); t7x=$(mktemp); taskset -c 7 ./bin/lb_rcv -i 129.57.109.231 -p 17757  -n $1 > $t7 2> $t7x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t8=$(mktemp); t8x=$(mktemp); taskset -c 16 ./bin/lb_rcv -i 129.57.109.231 -p 17758  -n $1 > $t8 2> $t8x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t9=$(mktemp); t9x=$(mktemp); taskset -c 17 ./bin/lb_rcv -i 129.57.109.231 -p 17759  -n $1 > $t9 2> $t9x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t10=$(mktemp); t10x=$(mktemp); taskset -c 18 ./bin/lb_rcv -i 129.57.109.231 -p 17760  -n $1 > $t10 2> $t10x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t11=$(mktemp); t11x=$(mktemp); taskset -c 19 ./bin/lb_rcv -i 129.57.109.231 -p 17761  -n $1 > $t11 2> $t11x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t12=$(mktemp); t12x=$(mktemp); taskset -c 20 ./bin/lb_rcv -i 129.57.109.231 -p 17762  -n $1 > $t12 2> $t12x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t13=$(mktemp); t13x=$(mktemp); taskset -c 21 ./bin/lb_rcv -i 129.57.109.231 -p 17763  -n $1 > $t13 2> $t13x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t14=$(mktemp); t14x=$(mktemp); taskset -c 22 ./bin/lb_rcv -i 129.57.109.231 -p 17764  -n $1 > $t14 2> $t14x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
t15=$(mktemp); t15x=$(mktemp); taskset -c 23 ./bin/lb_rcv -i 129.57.109.231 -p 17765  -n $1 > $t15 2> $t15x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO; 
sleep 0.1
wait
t=$(mktemp); 
for f in $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 $t9 $t10 $t11 $t12 $t13 $t14 $t15; 
    do 
        grep Interval $f  |sed 's/Interval: //'|sed 's/ us$//'|sed '1d' >> $t; 
    done
echo "Interval moments all dids; mean (ignore) stdev var skew kurt:"
get_moments < $t
echo "Mean Latency all dids, mean, stdev:"
tt=$(mktemp); 
for f in /tmp/tmp.*; 
    do 
        grep Latency $f  |sed 's/Latency: //'|sed 's/ us$//'|sed '1d' >> $tt; 
    done
echo "Latency moments all dids; mean (ignore) stdev var skew kurt:"
get_moments < $tt
echo "Processor utilization pattern accross dids:"
for f in  /tmp/rs_*_log ; 
    do 
        grep cpu $f|cut -f2|sort|uniq|wc -l; 
    done|sort -n|uniq
echo "Reassembly size Moments accross dids:"
ls -tl /tmp/rs_?????|cut -f5 -d' '|get_moments
echo "Number of unique reassembled sizes accross dids:"
ls -tl /tmp/rs_?????|cut -f5 -d' '|sort -n|uniq|wc -l
echo "number of packets written, all dids:"
for f in /tmp/rs_?????_log; 
    do 
        grep Writing $f;
    done|wc -l
#Sender:
#t=$(mktemp); tx=$(mktemp); f=/pm0/test/goodrich/urndm_100M.dat;mxid=15;mtu=9000;mxtck=6;mxlpi=19;time ./x4 $f $mxid $mtu $mxtck $mxlpi  >$t 2>$tx; sz=$(ls -l $f|cut -f5 -d' '); echo $(($sz*($mxlpi+1)))

echo "Unique seq # replicates all dids:"
for i in $(seq 0 116); 
    do 
        grep "seq = ${i} $" /tmp/rs_?????_log|wc -l; 
    done|sort -n|uniq
echo "Unique rcvd sizes, all dids:"
ls -lt /tmp/rs_?????|cut -f5 -d' '|sort -n|uniq
echo "Rcvd Packets sizes, all dids: "
grep Writing /tmp/rs_?????_log|cut -f2 -d ' '|sort -n|uniq
cat $t0 $t1 $t2 $t3 $t4 $t5 $t6 $t7 $t8 $t9 $t10 $t11 $t12 $t13 $t14 $t15
echo "tst_lb_rcv1 reported errors:"
cat $t0x $t1x $t2x $t3x $t4x $t5x $t6x $t7x $t8x $t9x $t10x $t11x $t12x $t13x $t14x $t15x  
