#!/bin/bash
tx=$(mktemp) 
taskset -c 23 bin/lb_rcv -i 129.57.109.231 -p 17750 -n $1  > $tx &
pid=$!
echo -n "pid="; echo $pid
sudo chrt -f -p 99 $pid  #SCHED_FIFO
wait $pid
#cut -f19 -d ' ' /tmp/rs_17750_0_log|gnuplot -p -e "p '-' u 1 w l"
grep 'lst = 1' /tmp/rs_17750_0_log|wc -l
t=$(mktemp) 
grep Latency $tx|sed 's/Latency: //'|sed 's/ us$//' > $t
gnuplot -p -e "set title 'Latency';p '$t' u 1 w l" &
hstgrm $t 20000 100 'Latency usec' 25000 &
echo "Latency:"
get_moments < $t
t1=$(mktemp) 
grep Interval $tx|sed 's/Interval: //'|sed 's/ us$//'|sed '1d' > $t1
gnuplot -p -e "set title 'Interval';p '$t1' u 1 w l" &
hstgrm $t1 20000 100 'Interval usec' 29500 &
echo "Interval:"
get_moments < $t1
echo $tx $t $t1
#for i in $(seq 0 117); do grep "seq = $i " /tmp/rs_17750_0_log|wc -l; done| grep $1|wc -l
echo $(($1 * 1024 * 1024 * 10))
ls /tmp/rs_17750_0 -l
