#!/bin/bash
#set -x
t0=$(mktemp); t0x=$(mktemp); taskset -c 0 ./bin/lb_rcv -v -i 129.57.109.231 -p 17750  -n $1 > $t0 2> $t0x &
pid=$!
sudo chrt -f -p 99 $pid  #SCHED_FIFO
wait
t=$(mktemp); for f in /tmp/tmp.*; do grep Interval $f  |sed 's/Interval: //'|sed 's/ us$//'|sed '1d' >> $t; done
echo "Interval moments across threads; mean (ignore) stdev var skew kurt:"
get_moments < $t
echo "Mean Latency across threads, mean, stdev:"
t1=$(mktemp); for f in /tmp/tmp.*; do grep Latency $f  |sed 's/Latency: //'|sed 's/ us$//'|sed '1d' >> $t1; done
echo "Latency moments across threads; mean (ignore) stdev var skew kurt:"
get_moments < $t1
echo "Processor utilization pattern:"
for f in  /tmp/rs_*_log ; do grep cpu $f|cut -f2|sort|uniq|wc -l; done|sort -n|uniq
echo "Reassembly size Moments accross IDs:"
ls -tl /tmp/rs_?????|cut -f5 -d' '|get_moments
echo "Number of unique reassembled sizes accross IDs:"
ls -tl /tmp/rs_?????|cut -f5 -d' '|sort -n|uniq|wc -l
echo "number of packets rec'd:"
for f in /tmp/rs_?????_log; do grep Received $f;done|wc -l
echo "Unique seq # replicates:"
for i in $(seq 0 116); do grep "seq = ${i} $" /tmp/rs_17750_log|wc -l; done|sort -n|uniq
echo "Unique rcvd sizes:"
ls -lt /tmp/rs_?????|cut -f5 -d' '|sort -n|uniq
