#!/bin/bash
set -x
# x4 <file> <max_data_id> <mtu> <max_tick> <loops>
#loops through ticks (hosts) and data_id streams in parallel 
t=$4
n=$2
l=$5
for k in $(seq 0 $l); do 
	for i in $(seq 0 $t); do 
		for d in $(seq 0 $n); do 
			#echo "./bin/pktzr_md -i 129.57.109.254 -p 19522 -e -t $i -d $d  -s $3  < $1"
			time nice -20  ./bin/pktzr_md -i 129.57.109.254 -p 19522 -e -t $i -d $d  -s $3  < $1 &
		done
	done
done
# t=$(mktemp); tx=$(mktemp); time ./x4 /pm0/test/goodrich/urndm_1M.dat 15 9000 100 10  >$t 2>$tx
