#!/bin/bash
# do_pid <num_events>

t=$(mktemp)
bin/pid -n $1 >$t
gnuplot -p \
	-e "set yrange [-1.1:1.1]" \
	-e "set title 'EJFAT PID Controller Simulation'" \
	-e "set xlabel 'Iteration' " \
	-e "set ylabel 'Signal' " \
	-e "p '$t' u 1 w l lc 'black' title 'process', '$t' u 2 w l lc 'red' title 'control', 0.5 w l lc 'green' title 'setPoint'"
rm $t
